Repository dotkom/design-system, pull requests merged in 2019-10, with the labels that each got.

#85 Use same tsconfig for linting as OWF, but with some alterations to fit the design system
  tsconfig.json
Labels: Hacktoberfest

#86 Refactor alert story to use the new markdown scheme
  src/components/alerts/Alert.stories.mdx
  src/components/alerts/Alert.stories.tsx
Labels: Hacktoberfest

#80 Fix static logos and make it easy to resize them
  src/components/logo/Logo.stories.mdx
  src/components/logo/StaticLogo.tsx
Labels: Hacktoberfest

#84 Add toggle switch to component library
  .gitignore
  src/components/buttons/ToggleSwitch.stories.mdx
  src/components/buttons/ToggleSwitch.tsx
  src/components/icons/CircleCheckmark.stories.js
  src/components/icons/CircleCheckmark.tsx
  src/components/icons/CircleCross.stories.js
  src/components/icons/CircleCross.tsx
  src/index.ts
Labels: Hacktoberfest

#83 Change paths internally and move shared to common
  .storybook/config.js
  src/common/global.ts
  src/common/layout.ts
  src/components/container/Container.stories.mdx
  src/components/container/Container.tsx
  src/components/forms/TextField.tsx
  src/index.ts
Labels: Priority: Low

#93 Fix lint and format
  .drone.yml
  package.json
  src/components/buttons/ToggleSwitch.tsx
  src/components/forms/TextField.tsx
  src/components/icons/CircleCheckmark.stories.js
  src/components/icons/CircleCheckmark.tsx
  src/components/icons/CircleCross.stories.js
  src/components/icons/CircleCross.tsx
  src/components/logo/StaticLogo.tsx
  src/components/tabs/Tab.tsx
  src/components/tabs/TabSelect.tsx
  src/components/tabs/Tabs.tsx
Labels: Priority: Critical

#95 Add instructions to README
  README.md
Labels: Priority: Medium
